version: '2'
services:
    madrassa-app:
        image: madrassa
        external_links:
            - madrassa-postgresql:postgresql
            - madrassa-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/madrassa
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    madrassa-postgresql:
        extends:
            file: postgresql.yml
            service: madrassa-postgresql
    madrassa-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: madrassa-elasticsearch
